### ISSUE TITLE
[BUG] Windows Defender detected virus in installer

### ISSUE THREAD

**Issue by lrasmus** [litrl/litrl_code#17]
**Describe the bug**
Upon downloading the installer from release (https://github.com/litrl/litrl_code/releases/download/exp-0.12.0.0/litrl-browser-experimental-0.12.0.0-public.exe) using Chrome, Windows Defender (on Win 10) reported that a Virus was detected in the installer.

**To Reproduce**
1. Go to Releases
2. Click on 'litrl-browser-experimental-0.12.0.0-public.exe'
3. Let program download
4. Virus warning reported by Windows Defender

**Expected behavior**
Download to not be flagged by anti-virus

**Screenshots**
![image](https://user-images.githubusercontent.com/967970/52579040-0969bd80-2deb-11e9-9d26-b389d2e5eacb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.12.0.0
 - Last URL: https://github.com/litrl/litrl_code/releases/download/exp-0.12.0.0/litrl-browser-experimental-0.12.0.0-public.exe

**Comment by brogly-zz** [comment]
@lrasmus - Well this isn't good! But it appears to be a false positive. I tried scanning it myself with Windows Defender and another Antivirus and it came back clean. I assigned the rest of our group to reinstall it again to see if this happens.

Which update of Windows Defender are you using? (under Search->Windows Defender Settings->Virus and Threat Protection->Virus and Threat Protection Updates

![image](https://user-images.githubusercontent.com/12432081/52582674-bf3d0800-2dfb-11e9-8adb-055e49c007d2.png)

**Comment by brogly-zz** [comment]
@lrasmus I will also rebuild the installer package; that might fix this.

**Comment by lrasmus** [comment]
Thanks @brogly !  I should have stated I figured this was a false positive, but wanted to report it.  Looks like my definition was slightly out of date.

![image](https://user-images.githubusercontent.com/967970/52583932-6028c480-2df6-11e9-997b-1521b3a6adaf.png)

Just updated, and re-ran download.  No issues reported this time.  Not sure if it was my outdated definitions, or if you already pushed up rebuilt installer.

**Comment by brogly-zz** [comment]
@lrasmus It must be your updated definitions that fixed it - I did not rebuild the installer. Looks like this is OK then.

**Comment by lrasmus** [comment]
Thanks for the quick response, sorry for the false alarm!
