### ISSUE TITLE
Clarification on unpublished JOSS paper references

### ISSUE THREAD

**Issue by lrasmus** [litrl/litrl_code#18]
Two unpublished manuscripts ("Detecting Clickbait: Here’s how to Do it" and "Falsified News Detection Methodology") do not show in the PDF references as being unpublished.  It just lists authors, year and name.  https://github.com/openjournals/joss-papers/blob/joss.01208/joss.01208/10.21105.joss.01208.pdf

Would using "unpublished" instead of "article" help clarify in generated PDF?  Main concern is that it's not clear if this is article, blog post, white paper, etc.

**Comment by brogly-zz** [comment]
That's true - we wrote it like 

unpublished {Brogly,
	author = {Chris Brogly and Victoria L. Rubin},
	title = {Detecting Clickbait: Here’s how to Do it},
	note = {Unpublished Manuscript},
	year = {2019}
}

but the unpublished doesn't seem to do anything... do you have any suggestions? I will try and find a fix

**Comment by lrasmus** [comment]
Thanks again for quick reply @brogly - I'm wondering if we can ask @danielskatz for input.  I will post over to review thread.  May be a non-issue, I didn't see explicit requirements in journal guidelines on this, it's just my opinion/preference.

**Comment by lrasmus** [comment]
Wait - just saw updated PDF, looks all good now.  Will close, thanks!
