### ISSUE TITLE
[BUG] Some links on page are missing clickbait info due to encoding/javascript insertion

### ISSUE THREAD

**Issue by CBenghi** [litrl/litrl_code#20]
**Describe the bug**
Not all titles are highlighted on the page

**To Reproduce**
1. Go to "https://www.theguardian.com/international"
3. Scroll down to the "opinion" section.
4. Not all titles are marked with the expected clickbait color.

**Screenshots**
![image](https://user-images.githubusercontent.com/5476273/52652466-6ef2a280-2eee-11e9-8170-1363bad84886.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Version [0.12.0.0]
 - Last URL: https://www.theguardian.com/international

**Comment by brogly-zz** [comment]
@CBenghi This is related to #11 where some links may end up getting pulled off the page with some Javascript garbage; also encoding sometimes affects this - so the browser can't highlight those links because it doesn't have the same text in memory

**Comment by brogly-zz** [comment]
@CBenghi highlighting has been improved but is still not perfect - if you pull and try it again most of the opinion section should be highlighting
