### ISSUE TITLE
[BUG] Form ratio on high-dpi monitors

### ISSUE THREAD

**Issue by CBenghi** [litrl/litrl_code#21]
**Describe the bug**
When using the program in an high-dpi monitor some settings are not readable.

**To Reproduce**
1. Change the dpi settings in windows 10 for instance to to 200%
2. Click on 'Highlight options' button on the right hand side of the page.
3. See truncated text.

**Expected behavior**
All text should be readable, or have a tooltip help at least.

**Screenshots**
![image](https://user-images.githubusercontent.com/5476273/52652929-43bc8300-2eef-11e9-9511-3a982f2aabdb.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Version [0.12.0.0]
 - Last URL: Irrelevant

**Comment by brogly-zz** [comment]
@CBenghi Will provide a patch shortly.

**Comment by brogly-zz** [comment]
@CBenghi - I have duplicated the issue and am working on a fix. It might take a few more days but I'm hoping to resolve this shortly.

**Comment by brogly-zz** [comment]
@CBenghi - I've done my best to address this issue with some changes. The downside is that the form looks a little odd on normal DPI screens but it is usable up to 200% now.

**Comment by CBenghi** [comment]
thanks @brogly, I'll review tomorrow.
I'm in a busy time right now, but I'll do my best to complete the whole review in a couple of days.
Claudio

**Comment by brogly-zz** [comment]
Totally understand and thanks again!

**Comment by CBenghi** [comment]
Thanks, this works now.
Best,
Claudio
