### ISSUE TITLE
[FEATURE REQUEST] Automated unit tests

### ISSUE THREAD

**Issue by lrasmus** [litrl/litrl_code#22]
**Is your feature request related to a problem? Please describe.**
The JOSS reviewer checklist requests "automated tests or manual steps described so that the function of the software can be verified".  I cannot find these.

**Describe the solution you'd like**
Please create automated tests or manual steps to verify the functionality of the software.  This is outside of documentation on the use of the software.

**Comment by brogly-zz** [comment]
@lrasmus - Thanks - I was thinking about this earlier... would specific examples of the different detectors working properly cover this issue?

**Comment by lrasmus** [comment]
@brogly - yes, I think anything that consistently asserts correct behavior of the underlying detectors.  I'm basing this off recommendations from:
https://joss.readthedocs.io/en/latest/review_criteria.html#tests

Thanks!

**Comment by brogly-zz** [comment]
@lrasmus - I don't think we can get to the "Good" level on the JOSS recommendations for testing but I think we can hit "OK" with manual steps. If you pull, I've added test clickbait/satire/falsification documents in "litrl_code\manual_browser_test_files\" for test input. Note that some of these contain crude/offensive text due to the nature of the text and we obviously don't condone anything like that. There should be a nice file manager page when you go to "litrl_code\manual_browser_test_files\".

I've contacted the rest of our group to provide better manual testing examples for these detectors. Note  a lot of the "non-clickbait" headlines are on the ambiguous side from what I recall when they were last used in a qualitative study... I'm waiting on another RA to provide me with less ambiguous headlines to better display the abilities of the program.

So I guess my question is, if the added examples provide some clarity with respect to testing, would that address this issue and bring us up to the "OK" level with manual tests?

Thanks a lot - chris

**Comment by brogly-zz** [comment]
@lrasmus - also added a Testing page on the wiki https://github.com/litrl/litrl_code/wiki/Test-files-for-the-browser

**Comment by lrasmus** [comment]
Thanks @brogly - I had to set this aside over the weekend, but will get back to reviewing.  From my standpoint it's okay to meet the "Good" recommendation for testing.  What you've described sounds like it will work, and I'll confirm that's the case.

**Comment by lrasmus** [comment]
@brogly - is the expected behavior that not all headlines in the clickbait test file would get an assessment?  I am seeing several that are not color-coded at all, which to me seems incorrect.

Also, is it possible to indicate within the test file which ones are known false positives/false negatives?  I understand that you don't want to over-fit your model and so I appreciate the explanation that results aren't going to be 100% match.  I think you should indicate which ones you expect to differ, and if there's a reason why (that you know of), that would also be helpful.

**Comment by brogly-zz** [comment]
@lrasmus - can you send a screenshot? That's odd. They all highlight when I run it:

![image](https://user-images.githubusercontent.com/12432081/52979338-1403f400-33a3-11e9-81a7-8a33fd31bb37.png)

> Also, is it possible to indicate within the test file which ones are known false positives/false negatives? <

I have some examples of this for clickbait, which I can add in. For satire and falsifications, we don't really have this data to the best of my knowledge...

**Comment by lrasmus** [comment]
This happens reliably in both the installed version and the version I built from source.  Tested multiple times across multiple runs:
![image](https://user-images.githubusercontent.com/967970/52979838-182d1300-339d-11e9-80a6-469d9c3266bd.png)

For the examples and the false positive/negative comments, I believe you should be able to produce these.  It's okay to not have an explanation, however.  But if you're not able to tell us what's expected output from the system in a controlled set of tests, it's hard to assess that the system reliably produces the same results.

**Comment by brogly-zz** [comment]
@lrasmus - for the highlighting, this is a bug in the installer version that CBenghi brought up in #20 ... a patch is there for master if you pull. It is related to encoding.

As for the false-positives, I understand your concerns here. I think what I mean is I'm not sure what we have on hand aside from clickbait to show that. I'll have to go back to the other RAs who did work on these but we can definitely address it, and I'll let you know once I clarify this.

**Comment by brogly-zz** [comment]
@lrasmus I have again updated the clickbait_tests.html file with 10 false positives and 10 false negatives. I also labelled one for satire. If I included 3 for satire, 3 for non-satire, and then 3 for falsified and 3 for non-falsified, would you consider that sufficent for the "OK" level for testing?

**Comment by lrasmus** [comment]
My bad for missing CBenghi's report, sorry!  Clickbait test page is exactly what I was hoping for, thank you.  And that sounds like a great plan for the satire/falsified results as well.

**Comment by brogly-zz** [comment]
@lrasmus - Added requested tests for each of the 3 detectors.

**Comment by lrasmus** [comment]
Looks great, thanks!
