### ISSUE TITLE
Clarification on purpose in project summary

### ISSUE THREAD

**Issue by lrasmus** [litrl/litrl_code#25]
In the project README and corresponding JOSS paper, you claim the system helps by
"automatically detecting and highlighting fake news headlines and articles, to varying accuracy in real-world use"

I would remove the term "fake news" and provide more objective claims.  For example, clickbait is not necessarily fake or false.

**Comment by brogly-zz** [comment]
@lrasmus - Yes, this should be fixed. Will re-write and post here to avoid getting whedon to build the PDF a bunch of times

**Comment by brogly-zz** [comment]
@lrasmus  - here is a re-write: The LiT.RL News Verification (NV) Browser is a system that offers a first step counter-measure by automatically detecting and highlighting clickbait (to 94% accuracy on a test set of 5670 texts), satire (to 84% accuracy on a test set of 95 texts), and falsified text (to 71% accuracy on a test set of 28 texts). The browser was built to study the effectiveness of these deception detectors when applied to real-world internet use, where the accuracy of these detectors may vary considerably given the range of text online.

**Comment by lrasmus** [comment]
I think that is perfect, thank you so much for taking it under consideration.

**Comment by brogly-zz** [comment]
@lrasmus - My supervisor has suggested the following edit: The LiT.RL News Verification (NV) Browser is a system that offers a first step counter-measure by automatically detecting and highlighting clickbait (to 94% accuracy on a test set of 5670 texts), satirical fake news (to 84% accuracy on a test set of 95 texts), and fabricated news (to 71% accuracy on a test set of 28 texts). The browser was built to study the effectiveness of these deception detectors when applied to online news websites, where the accuracy of these detectors may vary considerably given the variety of styles, formats and content of online news.

Do you consider this acceptable before I rebuild the PDF?

**Comment by lrasmus** [comment]
@brogly - that sounds acceptable to me.  Thanks!
